package com.example.util

import com.example.data.model.AppLanguage

enum class StringKey {
    APP_NAME,
    DASHBOARD,
    INVENTORY,
    NEW_BILL,
    RENTALS,
    QUOTATIONS,
    CUSTOMERS,
    SETTINGS,
    ACTIVE_RENTALS,
    DUE_TODAY,
    OVERDUE,
    TOTAL_REVENUE,
    AVAILABLE_STOCK,
    QUICK_ACTIONS,
    CREATE_QUOTATION,
    ADD_ITEM,
    ADD_CUSTOMER,
    SEARCH_PLACEHOLDER,
    ALL_CATEGORIES,
    TENTS,
    COOKING,
    SLEEPING,
    LIGHTING,
    GEAR,
    ELECTRONICS,
    PRICE_PER_DAY,
    DEPOSIT,
    STOCK,
    AVAILABLE,
    RENTED,
    ACTION_EDIT,
    ACTION_DELETE,
    ACTION_SAVE,
    ACTION_CANCEL,
    ACTION_SELECT,
    CUSTOMER_NAME,
    CUSTOMER_PHONE,
    CUSTOMER_NIC,
    CUSTOMER_ADDRESS,
    RENTAL_DATES,
    START_DATE,
    END_DATE,
    RENTAL_DAYS,
    SUBTOTAL,
    DISCOUNT,
    GRAND_TOTAL,
    REFUNDABLE_DEPOSIT,
    CREATE_BILL,
    SAVE_QUOTATION,
    CONVERT_TO_BILL,
    MARK_RETURNED,
    GENERATE_PDF,
    SHARE_WHATSAPP,
    CALL_CUSTOMER,
    THEME_MODE,
    APP_COLOR_PALETTE,
    APP_LANGUAGE,
    BUSINESS_BRANDING,
    BUSINESS_NAME,
    BUSINESS_ADDRESS,
    BUSINESS_PHONE,
    BUSINESS_EMAIL,
    TERMS_CONDITIONS,
    UPLOAD_LOGO,
    SELECT_LOGO,
    LOGO_SAVED,
    SUCCESS,
    ERROR,
    STOCK_UNAVAILABLE,
    RETURN_NOTIFICATION_TITLE,
    RETURN_NOTIFICATION_BODY,
    NO_DATA,
    BILL_NUMBER,
    QUOTE_NUMBER,
    STATUS
}

object Localization {
    private val englishMap = mapOf(
        StringKey.APP_NAME to "CampRent Pro",
        StringKey.DASHBOARD to "Dashboard",
        StringKey.INVENTORY to "Inventory",
        StringKey.NEW_BILL to "New Bill",
        StringKey.RENTALS to "Rentals",
        StringKey.QUOTATIONS to "Quotations",
        StringKey.CUSTOMERS to "Customers (CRM)",
        StringKey.SETTINGS to "Settings",
        StringKey.ACTIVE_RENTALS to "Active Rentals",
        StringKey.DUE_TODAY to "Due Today",
        StringKey.OVERDUE to "Overdue",
        StringKey.TOTAL_REVENUE to "Total Revenue",
        StringKey.AVAILABLE_STOCK to "Available Stock",
        StringKey.QUICK_ACTIONS to "Quick Actions",
        StringKey.CREATE_QUOTATION to "Create Quotation",
        StringKey.ADD_ITEM to "Add New Item",
        StringKey.ADD_CUSTOMER to "Add Customer",
        StringKey.SEARCH_PLACEHOLDER to "Search items, customers, bills...",
        StringKey.ALL_CATEGORIES to "All Categories",
        StringKey.TENTS to "Tents & Shelters",
        StringKey.COOKING to "Cooking & BBQ",
        StringKey.SLEEPING to "Sleeping & Mats",
        StringKey.LIGHTING to "Lighting & Power",
        StringKey.GEAR to "Hiking Gear",
        StringKey.ELECTRONICS to "Electronics",
        StringKey.PRICE_PER_DAY to "Daily Price",
        StringKey.DEPOSIT to "Security Deposit",
        StringKey.STOCK to "Total Stock",
        StringKey.AVAILABLE to "Available",
        StringKey.RENTED to "Rented Out",
        StringKey.ACTION_EDIT to "Edit",
        StringKey.ACTION_DELETE to "Delete",
        StringKey.ACTION_SAVE to "Save",
        StringKey.ACTION_CANCEL to "Cancel",
        StringKey.ACTION_SELECT to "Select",
        StringKey.CUSTOMER_NAME to "Customer Name",
        StringKey.CUSTOMER_PHONE to "Phone Number",
        StringKey.CUSTOMER_NIC to "NIC / Passport No.",
        StringKey.CUSTOMER_ADDRESS to "Customer Address",
        StringKey.RENTAL_DATES to "Rental Period",
        StringKey.START_DATE to "Start Date",
        StringKey.END_DATE to "Return Date",
        StringKey.RENTAL_DAYS to "Days",
        StringKey.SUBTOTAL to "Subtotal",
        StringKey.DISCOUNT to "Discount",
        StringKey.GRAND_TOTAL to "Grand Total",
        StringKey.REFUNDABLE_DEPOSIT to "Refundable Deposit",
        StringKey.CREATE_BILL to "Generate Rental Bill",
        StringKey.SAVE_QUOTATION to "Save Quotation",
        StringKey.CONVERT_TO_BILL to "1-Click Convert to Bill",
        StringKey.MARK_RETURNED to "Mark Items Returned",
        StringKey.GENERATE_PDF to "Generate Pro PDF",
        StringKey.SHARE_WHATSAPP to "Share via WhatsApp",
        StringKey.CALL_CUSTOMER to "Call Customer",
        StringKey.THEME_MODE to "Theme Mode",
        StringKey.APP_COLOR_PALETTE to "App Color Palette",
        StringKey.APP_LANGUAGE to "App Language (භාෂාව)",
        StringKey.BUSINESS_BRANDING to "Business Branding & Invoice",
        StringKey.BUSINESS_NAME to "Business Name",
        StringKey.BUSINESS_ADDRESS to "Business Address",
        StringKey.BUSINESS_PHONE to "Business Phone",
        StringKey.BUSINESS_EMAIL to "Business Email",
        StringKey.TERMS_CONDITIONS to "Terms & Conditions",
        StringKey.UPLOAD_LOGO to "Change Business Logo",
        StringKey.SELECT_LOGO to "Choose Logo from Gallery",
        StringKey.LOGO_SAVED to "Logo updated successfully",
        StringKey.SUCCESS to "Success",
        StringKey.ERROR to "Error",
        StringKey.STOCK_UNAVAILABLE to "Selected quantity exceeds available stock!",
        StringKey.RETURN_NOTIFICATION_TITLE to "Camping Gear Due for Return Today!",
        StringKey.RETURN_NOTIFICATION_BODY to "Rental #%s for %s is scheduled for return today.",
        StringKey.NO_DATA to "No records found.",
        StringKey.BILL_NUMBER to "Bill #",
        StringKey.QUOTE_NUMBER to "Quote #",
        StringKey.STATUS to "Status"
    )

    private val sinhalaMap = mapOf(
        StringKey.APP_NAME to "CampRent Pro",
        StringKey.DASHBOARD to "ප්‍රධාන පුවරුව",
        StringKey.INVENTORY to "භාණ්ඩ ලැයිස්තුව",
        StringKey.NEW_BILL to "අලුත් බිලක්",
        StringKey.RENTALS to "කුලියට දීම්",
        StringKey.QUOTATIONS to "මිල ගණන් (Quotations)",
        StringKey.CUSTOMERS to "පාරිභෝගිකයින් (CRM)",
        StringKey.SETTINGS to "සැකසුම්",
        StringKey.ACTIVE_RENTALS to "ක්‍රියාකාරී කුලී",
        StringKey.DUE_TODAY to "අද බාරදිය යුතු",
        StringKey.OVERDUE to "කල් ඉකුත් වූ",
        StringKey.TOTAL_REVENUE to "මුළු ආදායම",
        StringKey.AVAILABLE_STOCK to "තිබෙන තොගය",
        StringKey.QUICK_ACTIONS to "ඉක්මන් ක්‍රියාමාර්ග",
        StringKey.CREATE_QUOTATION to "Quotation එකක් හදන්න",
        StringKey.ADD_ITEM to "අලුත් භාණ්ඩයක් එක්කරන්න",
        StringKey.ADD_CUSTOMER to "පාරිභෝගිකයෙකු එක්කරන්න",
        StringKey.SEARCH_PLACEHOLDER to "භාණ්ඩ, පාරිභෝගිකයින්, බිල්පත් සොයන්න...",
        StringKey.ALL_CATEGORIES to "සියලුම වර්ග",
        StringKey.TENTS to "කූඩාරම් (Tents)",
        StringKey.COOKING to "උයන පිහින උපකරණ",
        StringKey.SLEEPING to "ස්ලීපින් බෑග් සහ මැට්",
        StringKey.LIGHTING to "විදුලි ලාම්පු සහ බලය",
        StringKey.GEAR to "කඳු නැගීමේ උපකරණ",
        StringKey.ELECTRONICS to "ඉලෙක්ට්‍රොනික",
        StringKey.PRICE_PER_DAY to "දිනකට ගාස්තුව",
        StringKey.DEPOSIT to "ඇප තැන්පතුව (Deposit)",
        StringKey.STOCK to "මුළු තොගය",
        StringKey.AVAILABLE to "ඉතිරි ප්‍රමාණය",
        StringKey.RENTED to "කුලියට දී ඇති",
        StringKey.ACTION_EDIT to "වෙනස් කරන්න",
        StringKey.ACTION_DELETE to "මකා දමන්න",
        StringKey.ACTION_SAVE to "සුරකින්න",
        StringKey.ACTION_CANCEL to "අවලංගු කරන්න",
        StringKey.ACTION_SELECT to "තෝරන්න",
        StringKey.CUSTOMER_NAME to "පාරිභෝගික නම",
        StringKey.CUSTOMER_PHONE to "දුරකථන අංකය",
        StringKey.CUSTOMER_NIC to "ජා.හැ. අංකය / විදේශගමන් බලපත්‍රය",
        StringKey.CUSTOMER_ADDRESS to "ලිපිනය",
        StringKey.RENTAL_DATES to "කුලී කාලසීමාව",
        StringKey.START_DATE to "ආරම්භක දිනය",
        StringKey.END_DATE to "ආපසු දෙන දිනය",
        StringKey.RENTAL_DAYS to "දින ගණන",
        StringKey.SUBTOTAL to "උප එකතුව",
        StringKey.DISCOUNT to "වට්ටම",
        StringKey.GRAND_TOTAL to "මුළු මුදල",
        StringKey.REFUNDABLE_DEPOSIT to "නැවත දෙන ඇප මුදල",
        StringKey.CREATE_BILL to "බිල්පත සාදන්න",
        StringKey.SAVE_QUOTATION to "Quotation එක සුරකින්න",
        StringKey.CONVERT_TO_BILL to "තප්පරයෙන් Bill එකට හරවන්න",
        StringKey.MARK_RETURNED to "බඩු බාරගත්තා ලෙස ලකුණු කරන්න",
        StringKey.GENERATE_PDF to "PDF Invoice එක සාදන්න",
        StringKey.SHARE_WHATSAPP to "WhatsApp හරහා යවන්න",
        StringKey.CALL_CUSTOMER to "ඇමතුමක් ගන්න",
        StringKey.THEME_MODE to "තේමා මාදිලිය (Theme)",
        StringKey.APP_COLOR_PALETTE to "ඇප් එකේ වර්ණ පද්ධතිය",
        StringKey.APP_LANGUAGE to "භාෂාව (Language)",
        StringKey.BUSINESS_BRANDING to "ව්‍යාපාරික තොරතුරු සහ ලාංඡනය",
        StringKey.BUSINESS_NAME to "ආයතනයේ නම",
        StringKey.BUSINESS_ADDRESS to "ලිපිනය",
        StringKey.BUSINESS_PHONE to "දුරකථන අංකය",
        StringKey.BUSINESS_EMAIL to "විද්‍යුත් තැපෑල",
        StringKey.BUSINESS_EMAIL to "Email",
        StringKey.TERMS_CONDITIONS to "කොන්දේසි",
        StringKey.UPLOAD_LOGO to "ව්‍යාපාරික ලාංඡනය (Logo) වෙනස් කරන්න",
        StringKey.SELECT_LOGO to "Gallery එකෙන් Logo එකක් තෝරන්න",
        StringKey.LOGO_SAVED to "Logo එක සාර්ථකව වෙනස් විය",
        StringKey.SUCCESS to "සාර්ථකයි",
        StringKey.ERROR to "දෝෂයක්",
        StringKey.STOCK_UNAVAILABLE to "තෝරාගත් ප්‍රමාණය තිබෙන තොගයට වඩා වැඩිය!",
        StringKey.RETURN_NOTIFICATION_TITLE to "කෑම්පින් බඩු අද ආපසු බාරදිය යුතුයි!",
        StringKey.RETURN_NOTIFICATION_BODY to "%s ගේ අංක %s බිල්පතේ බඩු අද ආපසු බාරදිය යුතුයි.",
        StringKey.NO_DATA to "තොරතුරු කිසිවක් නැත.",
        StringKey.BILL_NUMBER to "බිල් අංකය #",
        StringKey.QUOTE_NUMBER to "Quote #",
        StringKey.STATUS to "තත්ත්වය"
    )

    fun getString(key: StringKey, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.SINHALA -> sinhalaMap[key] ?: englishMap[key] ?: key.name
            AppLanguage.ENGLISH -> englishMap[key] ?: key.name
        }
    }
}
